FROM node:22-bookworm-slim AS build

WORKDIR /app

RUN corepack enable &&  corepack prepare pnpm@9.0.0 --activate 

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

COPY packages/schemas/package.json packages/schemas/package.json
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json

RUN pnpm install --frozen-lockfile

COPY packages/schemas packages/schemas
COPY apps/web   apps/web

RUN pnpm --filter @bastion/schemas build
RUN pnpm --filter web build

FROM nginx:alpine AS production

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/apps/web/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g", "daemon off;"]
